# Copyright (c) 2026 Gazuua. All rights reserved. Licensed under the MIT License.
{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
{{- end }}
