# Copyright (c) 2026 Gazuua. All rights reserved. Licensed under the MIT License.
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: apex-secret-store
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: apex-pipeline
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccount | quote }}
{{- end }}
