# Copyright (c) 2026 Gazuua. All rights reserved. Licensed under the MIT License.
{{- if .Values.externalSecrets.enabled }}
{{- range $name, $svc := .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}-external
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: apex-pipeline
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: apex-secret-store
    kind: SecretStore
  target:
    name: {{ $svc.targetSecret }}
    creationPolicy: Owner
  data:
    {{- range $svc.keys }}
    - secretKey: {{ .envVar }}
      remoteRef:
        key: {{ $.Values.externalSecrets.aws.secretPrefix }}/{{ $name }}
        property: {{ .property }}
    {{- end }}
{{- end }}
{{- end }}
