# Copyright (c) 2026 Gazuua. All rights reserved. Licensed under the MIT License.
{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "apex-common.fullname" . }}
  labels:
    {{- include "apex-common.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
{{- if and .Values.rollouts .Values.rollouts.enabled }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
{{- else }}
    apiVersion: apps/v1
    kind: Deployment
{{- end }}
    name: {{ include "apex-common.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
{{- end }}
